// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/auth/auth_api.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AppCode       string                 `protobuf:"bytes,3,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	SsoToken      string                 `protobuf:"bytes,5,opt,name=sso_token,json=ssoToken,proto3" json:"sso_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetSsoToken() string {
	if x != nil {
		return x.SsoToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ExchangeSSORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SsoToken      string                 `protobuf:"bytes,1,opt,name=sso_token,json=ssoToken,proto3" json:"sso_token,omitempty"`
	AppCode       string                 `protobuf:"bytes,2,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSSORequest) Reset() {
	*x = ExchangeSSORequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSSORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSSORequest) ProtoMessage() {}

func (x *ExchangeSSORequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSSORequest.ProtoReflect.Descriptor instead.
func (*ExchangeSSORequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeSSORequest) GetSsoToken() string {
	if x != nil {
		return x.SsoToken
	}
	return ""
}

func (x *ExchangeSSORequest) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *ExchangeSSORequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ExchangeSSOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeSSOResponse) Reset() {
	*x = ExchangeSSOResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeSSOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeSSOResponse) ProtoMessage() {}

func (x *ExchangeSSOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeSSOResponse.ProtoReflect.Descriptor instead.
func (*ExchangeSSOResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeSSOResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeSSOResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ExchangeSSOResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExchangeSSOResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppCode       string                 `protobuf:"bytes,1,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *LogoutRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SendPhoneCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPhoneCodeRequest) Reset() {
	*x = SendPhoneCodeRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPhoneCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeRequest) ProtoMessage() {}

func (x *SendPhoneCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeRequest.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{10}
}

func (x *SendPhoneCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendPhoneCodeRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

type SendPhoneCodeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	CooldownSeconds int32                  `protobuf:"varint,2,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DebugCode       string                 `protobuf:"bytes,4,opt,name=debug_code,json=debugCode,proto3" json:"debug_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendPhoneCodeResponse) Reset() {
	*x = SendPhoneCodeResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPhoneCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeResponse) ProtoMessage() {}

func (x *SendPhoneCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeResponse.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{11}
}

func (x *SendPhoneCodeResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SendPhoneCodeResponse) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

func (x *SendPhoneCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendPhoneCodeResponse) GetDebugCode() string {
	if x != nil {
		return x.DebugCode
	}
	return ""
}

type PhoneAuthEntryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phone            string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	VerificationCode string                 `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	AppCode          string                 `protobuf:"bytes,3,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	DeviceId         string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhoneAuthEntryRequest) Reset() {
	*x = PhoneAuthEntryRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneAuthEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneAuthEntryRequest) ProtoMessage() {}

func (x *PhoneAuthEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneAuthEntryRequest.ProtoReflect.Descriptor instead.
func (*PhoneAuthEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{12}
}

func (x *PhoneAuthEntryRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneAuthEntryRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

func (x *PhoneAuthEntryRequest) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *PhoneAuthEntryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type PhoneAuthEntryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	AccessToken     string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId          int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username        string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Email           string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	ShouldBindEmail bool                   `protobuf:"varint,8,opt,name=should_bind_email,json=shouldBindEmail,proto3" json:"should_bind_email,omitempty"`
	Message         string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	SsoToken        string                 `protobuf:"bytes,10,opt,name=sso_token,json=ssoToken,proto3" json:"sso_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PhoneAuthEntryResponse) Reset() {
	*x = PhoneAuthEntryResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneAuthEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneAuthEntryResponse) ProtoMessage() {}

func (x *PhoneAuthEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneAuthEntryResponse.ProtoReflect.Descriptor instead.
func (*PhoneAuthEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{13}
}

func (x *PhoneAuthEntryResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PhoneAuthEntryResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetShouldBindEmail() bool {
	if x != nil {
		return x.ShouldBindEmail
	}
	return false
}

func (x *PhoneAuthEntryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PhoneAuthEntryResponse) GetSsoToken() string {
	if x != nil {
		return x.SsoToken
	}
	return ""
}

type PhonePasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AppCode       string                 `protobuf:"bytes,3,opt,name=app_code,json=appCode,proto3" json:"app_code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonePasswordLoginRequest) Reset() {
	*x = PhonePasswordLoginRequest{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonePasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonePasswordLoginRequest) ProtoMessage() {}

func (x *PhonePasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonePasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PhonePasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{14}
}

func (x *PhonePasswordLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhonePasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PhonePasswordLoginRequest) GetAppCode() string {
	if x != nil {
		return x.AppCode
	}
	return ""
}

func (x *PhonePasswordLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type PhonePasswordLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	SsoToken      string                 `protobuf:"bytes,7,opt,name=sso_token,json=ssoToken,proto3" json:"sso_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhonePasswordLoginResponse) Reset() {
	*x = PhonePasswordLoginResponse{}
	mi := &file_proto_auth_auth_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhonePasswordLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhonePasswordLoginResponse) ProtoMessage() {}

func (x *PhonePasswordLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhonePasswordLoginResponse.ProtoReflect.Descriptor instead.
func (*PhonePasswordLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_api_proto_rawDescGZIP(), []int{15}
}

func (x *PhonePasswordLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PhonePasswordLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PhonePasswordLoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PhonePasswordLoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PhonePasswordLoginResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhonePasswordLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PhonePasswordLoginResponse) GetSsoToken() string {
	if x != nil {
		return x.SsoToken
	}
	return ""
}

var File_proto_auth_auth_api_proto protoreflect.FileDescriptor

const file_proto_auth_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x19proto/auth/auth_api.proto\x12\x04user\"~\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bapp_code\x18\x03 \x01(\tR\aappCode\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\xa9\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1b\n" +
	"\tsso_token\x18\x05 \x01(\tR\bssoToken\"+\n" +
	"\x13RefreshTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"i\n" +
	"\x12ExchangeSSORequest\x12\x1b\n" +
	"\tsso_token\x18\x01 \x01(\tR\bssoToken\x12\x19\n" +
	"\bapp_code\x18\x02 \x01(\tR\aappCode\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\x92\x01\n" +
	"\x13ExchangeSSOResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"G\n" +
	"\rLogoutRequest\x12\x19\n" +
	"\bapp_code\x18\x01 \x01(\tR\aappCode\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"J\n" +
	"\x13VerifyTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"B\n" +
	"\x14SendPhoneCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\"\x93\x01\n" +
	"\x15SendPhoneCodeResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12)\n" +
	"\x10cooldown_seconds\x18\x02 \x01(\x05R\x0fcooldownSeconds\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"debug_code\x18\x04 \x01(\tR\tdebugCode\"\x92\x01\n" +
	"\x15PhoneAuthEntryRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12+\n" +
	"\x11verification_code\x18\x02 \x01(\tR\x10verificationCode\x12\x19\n" +
	"\bapp_code\x18\x03 \x01(\tR\aappCode\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\xbc\x02\n" +
	"\x16PhoneAuthEntryResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12*\n" +
	"\x11should_bind_email\x18\b \x01(\bR\x0fshouldBindEmail\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x12\x1b\n" +
	"\tsso_token\x18\n" +
	" \x01(\tR\bssoToken\"\x85\x01\n" +
	"\x19PhonePasswordLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bapp_code\x18\x03 \x01(\tR\aappCode\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\"\xe6\x01\n" +
	"\x1aPhonePasswordLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1b\n" +
	"\tsso_token\x18\a \x01(\tR\bssoToken2\xb3\x04\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12E\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponse\x12B\n" +
	"\vExchangeSSO\x12\x18.user.ExchangeSSORequest\x1a\x19.user.ExchangeSSOResponse\x123\n" +
	"\x06Logout\x12\x13.user.LogoutRequest\x1a\x14.user.LogoutResponse\x12B\n" +
	"\vVerifyToken\x12\x18.user.VerifyTokenRequest\x1a\x19.user.VerifyTokenResponse\x12H\n" +
	"\rSendPhoneCode\x12\x1a.user.SendPhoneCodeRequest\x1a\x1b.user.SendPhoneCodeResponse\x12K\n" +
	"\x0ePhoneAuthEntry\x12\x1b.user.PhoneAuthEntryRequest\x1a\x1c.user.PhoneAuthEntryResponse\x12W\n" +
	"\x12PhonePasswordLogin\x12\x1f.user.PhonePasswordLoginRequest\x1a .user.PhonePasswordLoginResponseB'Z%github.com/luckysxx/common/proto/authb\x06proto3"

var (
	file_proto_auth_auth_api_proto_rawDescOnce sync.Once
	file_proto_auth_auth_api_proto_rawDescData []byte
)

func file_proto_auth_auth_api_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_api_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_api_proto_rawDesc), len(file_proto_auth_auth_api_proto_rawDesc)))
	})
	return file_proto_auth_auth_api_proto_rawDescData
}

var file_proto_auth_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_auth_auth_api_proto_goTypes = []any{
	(*LoginRequest)(nil),               // 0: user.LoginRequest
	(*LoginResponse)(nil),              // 1: user.LoginResponse
	(*RefreshTokenRequest)(nil),        // 2: user.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),       // 3: user.RefreshTokenResponse
	(*ExchangeSSORequest)(nil),         // 4: user.ExchangeSSORequest
	(*ExchangeSSOResponse)(nil),        // 5: user.ExchangeSSOResponse
	(*LogoutRequest)(nil),              // 6: user.LogoutRequest
	(*LogoutResponse)(nil),             // 7: user.LogoutResponse
	(*VerifyTokenRequest)(nil),         // 8: user.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),        // 9: user.VerifyTokenResponse
	(*SendPhoneCodeRequest)(nil),       // 10: user.SendPhoneCodeRequest
	(*SendPhoneCodeResponse)(nil),      // 11: user.SendPhoneCodeResponse
	(*PhoneAuthEntryRequest)(nil),      // 12: user.PhoneAuthEntryRequest
	(*PhoneAuthEntryResponse)(nil),     // 13: user.PhoneAuthEntryResponse
	(*PhonePasswordLoginRequest)(nil),  // 14: user.PhonePasswordLoginRequest
	(*PhonePasswordLoginResponse)(nil), // 15: user.PhonePasswordLoginResponse
}
var file_proto_auth_auth_api_proto_depIdxs = []int32{
	0,  // 0: user.AuthService.Login:input_type -> user.LoginRequest
	2,  // 1: user.AuthService.RefreshToken:input_type -> user.RefreshTokenRequest
	4,  // 2: user.AuthService.ExchangeSSO:input_type -> user.ExchangeSSORequest
	6,  // 3: user.AuthService.Logout:input_type -> user.LogoutRequest
	8,  // 4: user.AuthService.VerifyToken:input_type -> user.VerifyTokenRequest
	10, // 5: user.AuthService.SendPhoneCode:input_type -> user.SendPhoneCodeRequest
	12, // 6: user.AuthService.PhoneAuthEntry:input_type -> user.PhoneAuthEntryRequest
	14, // 7: user.AuthService.PhonePasswordLogin:input_type -> user.PhonePasswordLoginRequest
	1,  // 8: user.AuthService.Login:output_type -> user.LoginResponse
	3,  // 9: user.AuthService.RefreshToken:output_type -> user.RefreshTokenResponse
	5,  // 10: user.AuthService.ExchangeSSO:output_type -> user.ExchangeSSOResponse
	7,  // 11: user.AuthService.Logout:output_type -> user.LogoutResponse
	9,  // 12: user.AuthService.VerifyToken:output_type -> user.VerifyTokenResponse
	11, // 13: user.AuthService.SendPhoneCode:output_type -> user.SendPhoneCodeResponse
	13, // 14: user.AuthService.PhoneAuthEntry:output_type -> user.PhoneAuthEntryResponse
	15, // 15: user.AuthService.PhonePasswordLogin:output_type -> user.PhonePasswordLoginResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_api_proto_init() }
func file_proto_auth_auth_api_proto_init() {
	if File_proto_auth_auth_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_api_proto_rawDesc), len(file_proto_auth_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_api_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_api_proto_depIdxs,
		MessageInfos:      file_proto_auth_auth_api_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_api_proto = out.File
	file_proto_auth_auth_api_proto_goTypes = nil
	file_proto_auth_auth_api_proto_depIdxs = nil
}
