// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: note/note_api.proto

package note

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePasteRequest) Reset() {
	*x = CreatePasteRequest{}
	mi := &file_note_note_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePasteRequest) ProtoMessage() {}

func (x *CreatePasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePasteRequest.ProtoReflect.Descriptor instead.
func (*CreatePasteRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePasteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePasteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePasteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreatePasteRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type GetPasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PasteId       int64                  `protobuf:"varint,1,opt,name=paste_id,json=pasteId,proto3" json:"paste_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasteRequest) Reset() {
	*x = GetPasteRequest{}
	mi := &file_note_note_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasteRequest) ProtoMessage() {}

func (x *GetPasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasteRequest.ProtoReflect.Descriptor instead.
func (*GetPasteRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPasteRequest) GetPasteId() int64 {
	if x != nil {
		return x.PasteId
	}
	return 0
}

type ListPastesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPastesRequest) Reset() {
	*x = ListPastesRequest{}
	mi := &file_note_note_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPastesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPastesRequest) ProtoMessage() {}

func (x *ListPastesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPastesRequest.ProtoReflect.Descriptor instead.
func (*ListPastesRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{2}
}

type UpdatePasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PasteId       int64                  `protobuf:"varint,1,opt,name=paste_id,json=pasteId,proto3" json:"paste_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasteRequest) Reset() {
	*x = UpdatePasteRequest{}
	mi := &file_note_note_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasteRequest) ProtoMessage() {}

func (x *UpdatePasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasteRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasteRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePasteRequest) GetPasteId() int64 {
	if x != nil {
		return x.PasteId
	}
	return 0
}

func (x *UpdatePasteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePasteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePasteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdatePasteRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type PasteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ShortLink     string                 `protobuf:"bytes,4,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasteResponse) Reset() {
	*x = PasteResponse{}
	mi := &file_note_note_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteResponse) ProtoMessage() {}

func (x *PasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteResponse.ProtoReflect.Descriptor instead.
func (*PasteResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{4}
}

func (x *PasteResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PasteResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PasteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PasteResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

func (x *PasteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PasteResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PasteResponse) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *PasteResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PasteResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListPastesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pastes        []*PasteResponse       `protobuf:"bytes,1,rep,name=pastes,proto3" json:"pastes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPastesResponse) Reset() {
	*x = ListPastesResponse{}
	mi := &file_note_note_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPastesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPastesResponse) ProtoMessage() {}

func (x *ListPastesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPastesResponse.ProtoReflect.Descriptor instead.
func (*ListPastesResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListPastesResponse) GetPastes() []*PasteResponse {
	if x != nil {
		return x.Pastes
	}
	return nil
}

var File_note_note_api_proto protoreflect.FileDescriptor

const file_note_note_api_proto_rawDesc = "" +
	"\n" +
	"\x13note/note_api.proto\x12\x04note\"\x80\x01\n" +
	"\x12CreatePasteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\",\n" +
	"\x0fGetPasteRequest\x12\x19\n" +
	"\bpaste_id\x18\x01 \x01(\x03R\apasteId\"\x13\n" +
	"\x11ListPastesRequest\"\x9b\x01\n" +
	"\x12UpdatePasteRequest\x12\x19\n" +
	"\bpaste_id\x18\x01 \x01(\x03R\apasteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\"\x83\x02\n" +
	"\rPasteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"short_link\x18\x04 \x01(\tR\tshortLink\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"A\n" +
	"\x12ListPastesResponse\x12+\n" +
	"\x06pastes\x18\x01 \x03(\v2\x13.note.PasteResponseR\x06pastes2\x82\x02\n" +
	"\vNoteService\x12<\n" +
	"\vCreatePaste\x12\x18.note.CreatePasteRequest\x1a\x13.note.PasteResponse\x126\n" +
	"\bGetPaste\x12\x15.note.GetPasteRequest\x1a\x13.note.PasteResponse\x12?\n" +
	"\n" +
	"ListPastes\x12\x17.note.ListPastesRequest\x1a\x18.note.ListPastesResponse\x12<\n" +
	"\vUpdatePaste\x12\x18.note.UpdatePasteRequest\x1a\x13.note.PasteResponseB'Z%github.com/luckysxx/common/proto/noteb\x06proto3"

var (
	file_note_note_api_proto_rawDescOnce sync.Once
	file_note_note_api_proto_rawDescData []byte
)

func file_note_note_api_proto_rawDescGZIP() []byte {
	file_note_note_api_proto_rawDescOnce.Do(func() {
		file_note_note_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_note_api_proto_rawDesc), len(file_note_note_api_proto_rawDesc)))
	})
	return file_note_note_api_proto_rawDescData
}

var file_note_note_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_note_note_api_proto_goTypes = []any{
	(*CreatePasteRequest)(nil), // 0: note.CreatePasteRequest
	(*GetPasteRequest)(nil),    // 1: note.GetPasteRequest
	(*ListPastesRequest)(nil),  // 2: note.ListPastesRequest
	(*UpdatePasteRequest)(nil), // 3: note.UpdatePasteRequest
	(*PasteResponse)(nil),      // 4: note.PasteResponse
	(*ListPastesResponse)(nil), // 5: note.ListPastesResponse
}
var file_note_note_api_proto_depIdxs = []int32{
	4, // 0: note.ListPastesResponse.pastes:type_name -> note.PasteResponse
	0, // 1: note.NoteService.CreatePaste:input_type -> note.CreatePasteRequest
	1, // 2: note.NoteService.GetPaste:input_type -> note.GetPasteRequest
	2, // 3: note.NoteService.ListPastes:input_type -> note.ListPastesRequest
	3, // 4: note.NoteService.UpdatePaste:input_type -> note.UpdatePasteRequest
	4, // 5: note.NoteService.CreatePaste:output_type -> note.PasteResponse
	4, // 6: note.NoteService.GetPaste:output_type -> note.PasteResponse
	5, // 7: note.NoteService.ListPastes:output_type -> note.ListPastesResponse
	4, // 8: note.NoteService.UpdatePaste:output_type -> note.PasteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_note_note_api_proto_init() }
func file_note_note_api_proto_init() {
	if File_note_note_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_note_api_proto_rawDesc), len(file_note_note_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_note_api_proto_goTypes,
		DependencyIndexes: file_note_note_api_proto_depIdxs,
		MessageInfos:      file_note_note_api_proto_msgTypes,
	}.Build()
	File_note_note_api_proto = out.File
	file_note_note_api_proto_goTypes = nil
	file_note_note_api_proto_depIdxs = nil
}
