// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: note/note_api.proto

package note

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteService_CreatePaste_FullMethodName = "/note.NoteService/CreatePaste"
	NoteService_GetPaste_FullMethodName    = "/note.NoteService/GetPaste"
	NoteService_ListPastes_FullMethodName  = "/note.NoteService/ListPastes"
	NoteService_UpdatePaste_FullMethodName = "/note.NoteService/UpdatePaste"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	CreatePaste(ctx context.Context, in *CreatePasteRequest, opts ...grpc.CallOption) (*PasteResponse, error)
	GetPaste(ctx context.Context, in *GetPasteRequest, opts ...grpc.CallOption) (*PasteResponse, error)
	ListPastes(ctx context.Context, in *ListPastesRequest, opts ...grpc.CallOption) (*ListPastesResponse, error)
	UpdatePaste(ctx context.Context, in *UpdatePasteRequest, opts ...grpc.CallOption) (*PasteResponse, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) CreatePaste(ctx context.Context, in *CreatePasteRequest, opts ...grpc.CallOption) (*PasteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasteResponse)
	err := c.cc.Invoke(ctx, NoteService_CreatePaste_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetPaste(ctx context.Context, in *GetPasteRequest, opts ...grpc.CallOption) (*PasteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasteResponse)
	err := c.cc.Invoke(ctx, NoteService_GetPaste_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListPastes(ctx context.Context, in *ListPastesRequest, opts ...grpc.CallOption) (*ListPastesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPastesResponse)
	err := c.cc.Invoke(ctx, NoteService_ListPastes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdatePaste(ctx context.Context, in *UpdatePasteRequest, opts ...grpc.CallOption) (*PasteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasteResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdatePaste_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility.
type NoteServiceServer interface {
	CreatePaste(context.Context, *CreatePasteRequest) (*PasteResponse, error)
	GetPaste(context.Context, *GetPasteRequest) (*PasteResponse, error)
	ListPastes(context.Context, *ListPastesRequest) (*ListPastesResponse, error)
	UpdatePaste(context.Context, *UpdatePasteRequest) (*PasteResponse, error)
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteServiceServer struct{}

func (UnimplementedNoteServiceServer) CreatePaste(context.Context, *CreatePasteRequest) (*PasteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaste not implemented")
}
func (UnimplementedNoteServiceServer) GetPaste(context.Context, *GetPasteRequest) (*PasteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaste not implemented")
}
func (UnimplementedNoteServiceServer) ListPastes(context.Context, *ListPastesRequest) (*ListPastesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPastes not implemented")
}
func (UnimplementedNoteServiceServer) UpdatePaste(context.Context, *UpdatePasteRequest) (*PasteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaste not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}
func (UnimplementedNoteServiceServer) testEmbeddedByValue()                     {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	// If the following call panics, it indicates UnimplementedNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_CreatePaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreatePaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreatePaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreatePaste(ctx, req.(*CreatePasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetPaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetPaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetPaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetPaste(ctx, req.(*GetPasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListPastes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPastesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListPastes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListPastes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListPastes(ctx, req.(*ListPastesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdatePaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdatePaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdatePaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdatePaste(ctx, req.(*UpdatePasteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "note.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaste",
			Handler:    _NoteService_CreatePaste_Handler,
		},
		{
			MethodName: "GetPaste",
			Handler:    _NoteService_GetPaste_Handler,
		},
		{
			MethodName: "ListPastes",
			Handler:    _NoteService_ListPastes_Handler,
		},
		{
			MethodName: "UpdatePaste",
			Handler:    _NoteService_UpdatePaste_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "note/note_api.proto",
}
