// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: note/note_api.proto

package note

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteService_ListSnippets_FullMethodName              = "/note.NoteService/ListSnippets"
	NoteService_CreateSnippet_FullMethodName             = "/note.NoteService/CreateSnippet"
	NoteService_GetSnippet_FullMethodName                = "/note.NoteService/GetSnippet"
	NoteService_GetSnippetAIMetadata_FullMethodName      = "/note.NoteService/GetSnippetAIMetadata"
	NoteService_UpdateSnippet_FullMethodName             = "/note.NoteService/UpdateSnippet"
	NoteService_DeleteSnippet_FullMethodName             = "/note.NoteService/DeleteSnippet"
	NoteService_RestoreSnippet_FullMethodName            = "/note.NoteService/RestoreSnippet"
	NoteService_SetSnippetTags_FullMethodName            = "/note.NoteService/SetSnippetTags"
	NoteService_MoveSnippet_FullMethodName               = "/note.NoteService/MoveSnippet"
	NoteService_SearchSnippets_FullMethodName            = "/note.NoteService/SearchSnippets"
	NoteService_GetPublicSnippet_FullMethodName          = "/note.NoteService/GetPublicSnippet"
	NoteService_FavoriteSnippet_FullMethodName           = "/note.NoteService/FavoriteSnippet"
	NoteService_UnfavoriteSnippet_FullMethodName         = "/note.NoteService/UnfavoriteSnippet"
	NoteService_CreateSnippetFromTemplate_FullMethodName = "/note.NoteService/CreateSnippetFromTemplate"
	NoteService_CreateSnippetFromShare_FullMethodName    = "/note.NoteService/CreateSnippetFromShare"
	NoteService_ListRecentSnippets_FullMethodName        = "/note.NoteService/ListRecentSnippets"
	NoteService_ListSharedSnippets_FullMethodName        = "/note.NoteService/ListSharedSnippets"
	NoteService_ListFavoriteSnippets_FullMethodName      = "/note.NoteService/ListFavoriteSnippets"
	NoteService_ListGroups_FullMethodName                = "/note.NoteService/ListGroups"
	NoteService_GetGroup_FullMethodName                  = "/note.NoteService/GetGroup"
	NoteService_CreateGroup_FullMethodName               = "/note.NoteService/CreateGroup"
	NoteService_UpdateGroup_FullMethodName               = "/note.NoteService/UpdateGroup"
	NoteService_DeleteGroup_FullMethodName               = "/note.NoteService/DeleteGroup"
	NoteService_ListTags_FullMethodName                  = "/note.NoteService/ListTags"
	NoteService_CreateTag_FullMethodName                 = "/note.NoteService/CreateTag"
	NoteService_UpdateTag_FullMethodName                 = "/note.NoteService/UpdateTag"
	NoteService_DeleteTag_FullMethodName                 = "/note.NoteService/DeleteTag"
	NoteService_ListTemplates_FullMethodName             = "/note.NoteService/ListTemplates"
	NoteService_GetTemplate_FullMethodName               = "/note.NoteService/GetTemplate"
	NoteService_CreateTemplate_FullMethodName            = "/note.NoteService/CreateTemplate"
	NoteService_UpdateTemplate_FullMethodName            = "/note.NoteService/UpdateTemplate"
	NoteService_DeleteTemplate_FullMethodName            = "/note.NoteService/DeleteTemplate"
	NoteService_CreateShare_FullMethodName               = "/note.NoteService/CreateShare"
	NoteService_ListMyShares_FullMethodName              = "/note.NoteService/ListMyShares"
	NoteService_DeleteShare_FullMethodName               = "/note.NoteService/DeleteShare"
	NoteService_GetPublicShareByToken_FullMethodName     = "/note.NoteService/GetPublicShareByToken"
	NoteService_PresignUpload_FullMethodName             = "/note.NoteService/PresignUpload"
	NoteService_CompleteUpload_FullMethodName            = "/note.NoteService/CompleteUpload"
	NoteService_UploadFile_FullMethodName                = "/note.NoteService/UploadFile"
)

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteServiceClient interface {
	ListSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	GetSnippetAIMetadata(ctx context.Context, in *GetSnippetAIMetadataRequest, opts ...grpc.CallOption) (*SnippetAIMetadataResponse, error)
	UpdateSnippet(ctx context.Context, in *UpdateSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	DeleteSnippet(ctx context.Context, in *DeleteSnippetRequest, opts ...grpc.CallOption) (*DeleteSnippetResponse, error)
	RestoreSnippet(ctx context.Context, in *RestoreSnippetRequest, opts ...grpc.CallOption) (*RestoreSnippetResponse, error)
	SetSnippetTags(ctx context.Context, in *SetSnippetTagsRequest, opts ...grpc.CallOption) (*SetSnippetTagsResponse, error)
	// MoveSnippet 将片段移动到目标分组并设置排序权重。
	// group_id 省略时表示收集箱（未分组）；sort_order 省略时服务端自动追加到目标分组末尾。
	MoveSnippet(ctx context.Context, in *MoveSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	// 公开片段 — 不加 http 注解，保留手写 handler（无需鉴权）
	GetPublicSnippet(ctx context.Context, in *GetPublicSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	FavoriteSnippet(ctx context.Context, in *FavoriteSnippetRequest, opts ...grpc.CallOption) (*FavoriteSnippetResponse, error)
	UnfavoriteSnippet(ctx context.Context, in *UnfavoriteSnippetRequest, opts ...grpc.CallOption) (*FavoriteSnippetResponse, error)
	CreateSnippetFromTemplate(ctx context.Context, in *CreateSnippetFromTemplateRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	CreateSnippetFromShare(ctx context.Context, in *CreateSnippetFromShareRequest, opts ...grpc.CallOption) (*SnippetResponse, error)
	ListRecentSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	ListSharedSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	ListFavoriteSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
	CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*ShareResponse, error)
	ListMyShares(ctx context.Context, in *ListMySharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error)
	DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error)
	// 公开分享 — 不加 http 注解，保留手写 handler（无需鉴权）
	GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*PublicShareResponse, error)
	PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
	// 文件上传（兼容旧链路）— 不加 http 注解，保留手写 handler（二进制流）
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) ListSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_GetSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetSnippetAIMetadata(ctx context.Context, in *GetSnippetAIMetadataRequest, opts ...grpc.CallOption) (*SnippetAIMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetAIMetadataResponse)
	err := c.cc.Invoke(ctx, NoteService_GetSnippetAIMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateSnippet(ctx context.Context, in *UpdateSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdateSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteSnippet(ctx context.Context, in *DeleteSnippetRequest, opts ...grpc.CallOption) (*DeleteSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) RestoreSnippet(ctx context.Context, in *RestoreSnippetRequest, opts ...grpc.CallOption) (*RestoreSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_RestoreSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) SetSnippetTags(ctx context.Context, in *SetSnippetTagsRequest, opts ...grpc.CallOption) (*SetSnippetTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSnippetTagsResponse)
	err := c.cc.Invoke(ctx, NoteService_SetSnippetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) MoveSnippet(ctx context.Context, in *MoveSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_MoveSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) SearchSnippets(ctx context.Context, in *SearchSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, NoteService_SearchSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetPublicSnippet(ctx context.Context, in *GetPublicSnippetRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_GetPublicSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) FavoriteSnippet(ctx context.Context, in *FavoriteSnippetRequest, opts ...grpc.CallOption) (*FavoriteSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteSnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_FavoriteSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UnfavoriteSnippet(ctx context.Context, in *UnfavoriteSnippetRequest, opts ...grpc.CallOption) (*FavoriteSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FavoriteSnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_UnfavoriteSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateSnippetFromTemplate(ctx context.Context, in *CreateSnippetFromTemplateRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateSnippetFromTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateSnippetFromShare(ctx context.Context, in *CreateSnippetFromShareRequest, opts ...grpc.CallOption) (*SnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateSnippetFromShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListRecentSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListRecentSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListSharedSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListSharedSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListFavoriteSnippets(ctx context.Context, in *ListSnippetsRequest, opts ...grpc.CallOption) (*ListSnippetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnippetsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListFavoriteSnippets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, NoteService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*DeleteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGroupResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, NoteService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*TagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, NoteService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, NoteService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, NoteService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*ShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareResponse)
	err := c.cc.Invoke(ctx, NoteService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) ListMyShares(ctx context.Context, in *ListMySharesRequest, opts ...grpc.CallOption) (*ListSharesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharesResponse)
	err := c.cc.Invoke(ctx, NoteService_ListMyShares_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) DeleteShare(ctx context.Context, in *DeleteShareRequest, opts ...grpc.CallOption) (*DeleteShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteShareResponse)
	err := c.cc.Invoke(ctx, NoteService_DeleteShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) GetPublicShareByToken(ctx context.Context, in *GetPublicShareByTokenRequest, opts ...grpc.CallOption) (*PublicShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicShareResponse)
	err := c.cc.Invoke(ctx, NoteService_GetPublicShareByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) PresignUpload(ctx context.Context, in *PresignUploadRequest, opts ...grpc.CallOption) (*PresignUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresignUploadResponse)
	err := c.cc.Invoke(ctx, NoteService_PresignUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, NoteService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, NoteService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
// All implementations must embed UnimplementedNoteServiceServer
// for forward compatibility.
type NoteServiceServer interface {
	ListSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error)
	CreateSnippet(context.Context, *CreateSnippetRequest) (*SnippetResponse, error)
	GetSnippet(context.Context, *GetSnippetRequest) (*SnippetResponse, error)
	GetSnippetAIMetadata(context.Context, *GetSnippetAIMetadataRequest) (*SnippetAIMetadataResponse, error)
	UpdateSnippet(context.Context, *UpdateSnippetRequest) (*SnippetResponse, error)
	DeleteSnippet(context.Context, *DeleteSnippetRequest) (*DeleteSnippetResponse, error)
	RestoreSnippet(context.Context, *RestoreSnippetRequest) (*RestoreSnippetResponse, error)
	SetSnippetTags(context.Context, *SetSnippetTagsRequest) (*SetSnippetTagsResponse, error)
	// MoveSnippet 将片段移动到目标分组并设置排序权重。
	// group_id 省略时表示收集箱（未分组）；sort_order 省略时服务端自动追加到目标分组末尾。
	MoveSnippet(context.Context, *MoveSnippetRequest) (*SnippetResponse, error)
	SearchSnippets(context.Context, *SearchSnippetsRequest) (*ListSnippetsResponse, error)
	// 公开片段 — 不加 http 注解，保留手写 handler（无需鉴权）
	GetPublicSnippet(context.Context, *GetPublicSnippetRequest) (*SnippetResponse, error)
	FavoriteSnippet(context.Context, *FavoriteSnippetRequest) (*FavoriteSnippetResponse, error)
	UnfavoriteSnippet(context.Context, *UnfavoriteSnippetRequest) (*FavoriteSnippetResponse, error)
	CreateSnippetFromTemplate(context.Context, *CreateSnippetFromTemplateRequest) (*SnippetResponse, error)
	CreateSnippetFromShare(context.Context, *CreateSnippetFromShareRequest) (*SnippetResponse, error)
	ListRecentSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error)
	ListSharedSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error)
	ListFavoriteSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GroupResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*GroupResponse, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error)
	UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*TemplateResponse, error)
	CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
	CreateShare(context.Context, *CreateShareRequest) (*ShareResponse, error)
	ListMyShares(context.Context, *ListMySharesRequest) (*ListSharesResponse, error)
	DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error)
	// 公开分享 — 不加 http 注解，保留手写 handler（无需鉴权）
	GetPublicShareByToken(context.Context, *GetPublicShareByTokenRequest) (*PublicShareResponse, error)
	PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	// 文件上传（兼容旧链路）— 不加 http 注解，保留手写 handler（二进制流）
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	mustEmbedUnimplementedNoteServiceServer()
}

// UnimplementedNoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteServiceServer struct{}

func (UnimplementedNoteServiceServer) ListSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnippets not implemented")
}
func (UnimplementedNoteServiceServer) CreateSnippet(context.Context, *CreateSnippetRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnippet not implemented")
}
func (UnimplementedNoteServiceServer) GetSnippet(context.Context, *GetSnippetRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnippet not implemented")
}
func (UnimplementedNoteServiceServer) GetSnippetAIMetadata(context.Context, *GetSnippetAIMetadataRequest) (*SnippetAIMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnippetAIMetadata not implemented")
}
func (UnimplementedNoteServiceServer) UpdateSnippet(context.Context, *UpdateSnippetRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSnippet not implemented")
}
func (UnimplementedNoteServiceServer) DeleteSnippet(context.Context, *DeleteSnippetRequest) (*DeleteSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnippet not implemented")
}
func (UnimplementedNoteServiceServer) RestoreSnippet(context.Context, *RestoreSnippetRequest) (*RestoreSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnippet not implemented")
}
func (UnimplementedNoteServiceServer) SetSnippetTags(context.Context, *SetSnippetTagsRequest) (*SetSnippetTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSnippetTags not implemented")
}
func (UnimplementedNoteServiceServer) MoveSnippet(context.Context, *MoveSnippetRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveSnippet not implemented")
}
func (UnimplementedNoteServiceServer) SearchSnippets(context.Context, *SearchSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSnippets not implemented")
}
func (UnimplementedNoteServiceServer) GetPublicSnippet(context.Context, *GetPublicSnippetRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicSnippet not implemented")
}
func (UnimplementedNoteServiceServer) FavoriteSnippet(context.Context, *FavoriteSnippetRequest) (*FavoriteSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FavoriteSnippet not implemented")
}
func (UnimplementedNoteServiceServer) UnfavoriteSnippet(context.Context, *UnfavoriteSnippetRequest) (*FavoriteSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfavoriteSnippet not implemented")
}
func (UnimplementedNoteServiceServer) CreateSnippetFromTemplate(context.Context, *CreateSnippetFromTemplateRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnippetFromTemplate not implemented")
}
func (UnimplementedNoteServiceServer) CreateSnippetFromShare(context.Context, *CreateSnippetFromShareRequest) (*SnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnippetFromShare not implemented")
}
func (UnimplementedNoteServiceServer) ListRecentSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecentSnippets not implemented")
}
func (UnimplementedNoteServiceServer) ListSharedSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedSnippets not implemented")
}
func (UnimplementedNoteServiceServer) ListFavoriteSnippets(context.Context, *ListSnippetsRequest) (*ListSnippetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFavoriteSnippets not implemented")
}
func (UnimplementedNoteServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedNoteServiceServer) GetGroup(context.Context, *GetGroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedNoteServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedNoteServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedNoteServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*DeleteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedNoteServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedNoteServiceServer) CreateTag(context.Context, *CreateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedNoteServiceServer) UpdateTag(context.Context, *UpdateTagRequest) (*TagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedNoteServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedNoteServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedNoteServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedNoteServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedNoteServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*TemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedNoteServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedNoteServiceServer) CreateShare(context.Context, *CreateShareRequest) (*ShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedNoteServiceServer) ListMyShares(context.Context, *ListMySharesRequest) (*ListSharesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyShares not implemented")
}
func (UnimplementedNoteServiceServer) DeleteShare(context.Context, *DeleteShareRequest) (*DeleteShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShare not implemented")
}
func (UnimplementedNoteServiceServer) GetPublicShareByToken(context.Context, *GetPublicShareByTokenRequest) (*PublicShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicShareByToken not implemented")
}
func (UnimplementedNoteServiceServer) PresignUpload(context.Context, *PresignUploadRequest) (*PresignUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PresignUpload not implemented")
}
func (UnimplementedNoteServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedNoteServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedNoteServiceServer) mustEmbedUnimplementedNoteServiceServer() {}
func (UnimplementedNoteServiceServer) testEmbeddedByValue()                     {}

// UnsafeNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteServiceServer will
// result in compilation errors.
type UnsafeNoteServiceServer interface {
	mustEmbedUnimplementedNoteServiceServer()
}

func RegisterNoteServiceServer(s grpc.ServiceRegistrar, srv NoteServiceServer) {
	// If the following call panics, it indicates UnimplementedNoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteService_ServiceDesc, srv)
}

func _NoteService_ListSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListSnippets(ctx, req.(*ListSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateSnippet(ctx, req.(*CreateSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetSnippet(ctx, req.(*GetSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetSnippetAIMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnippetAIMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetSnippetAIMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetSnippetAIMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetSnippetAIMetadata(ctx, req.(*GetSnippetAIMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateSnippet(ctx, req.(*UpdateSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteSnippet(ctx, req.(*DeleteSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_RestoreSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).RestoreSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_RestoreSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).RestoreSnippet(ctx, req.(*RestoreSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_SetSnippetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSnippetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).SetSnippetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_SetSnippetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).SetSnippetTags(ctx, req.(*SetSnippetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_MoveSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).MoveSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_MoveSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).MoveSnippet(ctx, req.(*MoveSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_SearchSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).SearchSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_SearchSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).SearchSnippets(ctx, req.(*SearchSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetPublicSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetPublicSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetPublicSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetPublicSnippet(ctx, req.(*GetPublicSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_FavoriteSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).FavoriteSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_FavoriteSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).FavoriteSnippet(ctx, req.(*FavoriteSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UnfavoriteSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfavoriteSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UnfavoriteSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UnfavoriteSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UnfavoriteSnippet(ctx, req.(*UnfavoriteSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateSnippetFromTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnippetFromTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateSnippetFromTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateSnippetFromTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateSnippetFromTemplate(ctx, req.(*CreateSnippetFromTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateSnippetFromShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnippetFromShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateSnippetFromShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateSnippetFromShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateSnippetFromShare(ctx, req.(*CreateSnippetFromShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListRecentSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListRecentSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListRecentSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListRecentSnippets(ctx, req.(*ListSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListSharedSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListSharedSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListSharedSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListSharedSnippets(ctx, req.(*ListSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListFavoriteSnippets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnippetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListFavoriteSnippets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListFavoriteSnippets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListFavoriteSnippets(ctx, req.(*ListSnippetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CreateShare(ctx, req.(*CreateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_ListMyShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMySharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).ListMyShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_ListMyShares_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).ListMyShares(ctx, req.(*ListMySharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_DeleteShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).DeleteShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_DeleteShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).DeleteShare(ctx, req.(*DeleteShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_GetPublicShareByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicShareByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).GetPublicShareByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_GetPublicShareByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).GetPublicShareByToken(ctx, req.(*GetPublicShareByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_PresignUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).PresignUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_PresignUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).PresignUpload(ctx, req.(*PresignUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteService_ServiceDesc is the grpc.ServiceDesc for NoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "note.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnippets",
			Handler:    _NoteService_ListSnippets_Handler,
		},
		{
			MethodName: "CreateSnippet",
			Handler:    _NoteService_CreateSnippet_Handler,
		},
		{
			MethodName: "GetSnippet",
			Handler:    _NoteService_GetSnippet_Handler,
		},
		{
			MethodName: "GetSnippetAIMetadata",
			Handler:    _NoteService_GetSnippetAIMetadata_Handler,
		},
		{
			MethodName: "UpdateSnippet",
			Handler:    _NoteService_UpdateSnippet_Handler,
		},
		{
			MethodName: "DeleteSnippet",
			Handler:    _NoteService_DeleteSnippet_Handler,
		},
		{
			MethodName: "RestoreSnippet",
			Handler:    _NoteService_RestoreSnippet_Handler,
		},
		{
			MethodName: "SetSnippetTags",
			Handler:    _NoteService_SetSnippetTags_Handler,
		},
		{
			MethodName: "MoveSnippet",
			Handler:    _NoteService_MoveSnippet_Handler,
		},
		{
			MethodName: "SearchSnippets",
			Handler:    _NoteService_SearchSnippets_Handler,
		},
		{
			MethodName: "GetPublicSnippet",
			Handler:    _NoteService_GetPublicSnippet_Handler,
		},
		{
			MethodName: "FavoriteSnippet",
			Handler:    _NoteService_FavoriteSnippet_Handler,
		},
		{
			MethodName: "UnfavoriteSnippet",
			Handler:    _NoteService_UnfavoriteSnippet_Handler,
		},
		{
			MethodName: "CreateSnippetFromTemplate",
			Handler:    _NoteService_CreateSnippetFromTemplate_Handler,
		},
		{
			MethodName: "CreateSnippetFromShare",
			Handler:    _NoteService_CreateSnippetFromShare_Handler,
		},
		{
			MethodName: "ListRecentSnippets",
			Handler:    _NoteService_ListRecentSnippets_Handler,
		},
		{
			MethodName: "ListSharedSnippets",
			Handler:    _NoteService_ListSharedSnippets_Handler,
		},
		{
			MethodName: "ListFavoriteSnippets",
			Handler:    _NoteService_ListFavoriteSnippets_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _NoteService_ListGroups_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _NoteService_GetGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _NoteService_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _NoteService_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _NoteService_DeleteGroup_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _NoteService_ListTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _NoteService_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _NoteService_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _NoteService_DeleteTag_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _NoteService_ListTemplates_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _NoteService_GetTemplate_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _NoteService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _NoteService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _NoteService_DeleteTemplate_Handler,
		},
		{
			MethodName: "CreateShare",
			Handler:    _NoteService_CreateShare_Handler,
		},
		{
			MethodName: "ListMyShares",
			Handler:    _NoteService_ListMyShares_Handler,
		},
		{
			MethodName: "DeleteShare",
			Handler:    _NoteService_DeleteShare_Handler,
		},
		{
			MethodName: "GetPublicShareByToken",
			Handler:    _NoteService_GetPublicShareByToken_Handler,
		},
		{
			MethodName: "PresignUpload",
			Handler:    _NoteService_PresignUpload_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _NoteService_CompleteUpload_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _NoteService_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "note/note_api.proto",
}
