// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: note/note_api.proto

package note

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	GroupId       *int64                 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"` // 可选的所属分组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetRequest) Reset() {
	*x = CreateSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetRequest) ProtoMessage() {}

func (x *CreateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetRequest.ProtoReflect.Descriptor instead.
func (*CreateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSnippetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateSnippetRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateSnippetRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *CreateSnippetRequest) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type GetSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetRequest) Reset() {
	*x = GetSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetRequest) ProtoMessage() {}

func (x *GetSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetRequest.ProtoReflect.Descriptor instead.
func (*GetSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

type ListSnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"` // 按分组筛选
	TagId         *int64                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3,oneof" json:"tag_id,omitempty"`       // 按标签筛选
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`                       // 模糊搜索标题
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                          // 每页条数，默认 20，最大 100
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`                         // 游标分页（上一页返回的 next_cursor）
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`           // "updated_at" | "created_at" | "title" | "manual"，默认 "updated_at"
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`                 // 按可见性筛选：public / private / ""(全部)
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`                             // 按类型筛选：code / note / file / ""(全部)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnippetsRequest) Reset() {
	*x = ListSnippetsRequest{}
	mi := &file_note_note_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnippetsRequest) ProtoMessage() {}

func (x *ListSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnippetsRequest.ProtoReflect.Descriptor instead.
func (*ListSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListSnippetsRequest) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *ListSnippetsRequest) GetTagId() int64 {
	if x != nil && x.TagId != nil {
		return *x.TagId
	}
	return 0
}

func (x *ListSnippetsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListSnippetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSnippetsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSnippetsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListSnippetsRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListSnippetsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnippetRequest) Reset() {
	*x = UpdateSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnippetRequest) ProtoMessage() {}

func (x *UpdateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnippetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

func (x *UpdateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSnippetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateSnippetRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateSnippetRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type SnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	FileUrl       string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Language      string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Visibility    string                 `protobuf:"bytes,10,opt,name=visibility,proto3" json:"visibility,omitempty"`
	GroupId       int64                  `protobuf:"varint,11,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TagIds        []int64                `protobuf:"varint,14,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	SortOrder     int32                  `protobuf:"varint,15,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 在所属分组内的排序权重，值越小越靠前
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnippetResponse) Reset() {
	*x = SnippetResponse{}
	mi := &file_note_note_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnippetResponse) ProtoMessage() {}

func (x *SnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnippetResponse.ProtoReflect.Descriptor instead.
func (*SnippetResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{4}
}

func (x *SnippetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SnippetResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *SnippetResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SnippetResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SnippetResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SnippetResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SnippetResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SnippetResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *SnippetResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SnippetResponse) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *SnippetResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SnippetResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SnippetResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SnippetResponse) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *SnippetResponse) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListSnippetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*SnippetResponse     `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 空字符串 = 没有下一页
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnippetsResponse) Reset() {
	*x = ListSnippetsResponse{}
	mi := &file_note_note_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnippetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnippetsResponse) ProtoMessage() {}

func (x *ListSnippetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnippetsResponse.ProtoReflect.Descriptor instead.
func (*ListSnippetsResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListSnippetsResponse) GetSnippets() []*SnippetResponse {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *ListSnippetsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListSnippetsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DeleteSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnippetRequest) Reset() {
	*x = DeleteSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnippetRequest) ProtoMessage() {}

func (x *DeleteSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnippetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

type DeleteSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnippetResponse) Reset() {
	*x = DeleteSnippetResponse{}
	mi := &file_note_note_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnippetResponse) ProtoMessage() {}

func (x *DeleteSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnippetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnippetResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSnippetResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetSnippetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	TagIds        []int64                `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSnippetTagsRequest) Reset() {
	*x = SetSnippetTagsRequest{}
	mi := &file_note_note_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSnippetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSnippetTagsRequest) ProtoMessage() {}

func (x *SetSnippetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSnippetTagsRequest.ProtoReflect.Descriptor instead.
func (*SetSnippetTagsRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{8}
}

func (x *SetSnippetTagsRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

func (x *SetSnippetTagsRequest) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type SetSnippetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSnippetTagsResponse) Reset() {
	*x = SetSnippetTagsResponse{}
	mi := &file_note_note_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSnippetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSnippetTagsResponse) ProtoMessage() {}

func (x *SetSnippetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSnippetTagsResponse.ProtoReflect.Descriptor instead.
func (*SetSnippetTagsResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{9}
}

// MoveSnippetRequest 移动片段到指定分组并可选地设置排序权重。
// group_id 不传表示移动到收集箱（未分组）。
// sort_order 不传表示追加到目标分组末尾（由服务端计算 max+1）。
type MoveSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveSnippetRequest) Reset() {
	*x = MoveSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSnippetRequest) ProtoMessage() {}

func (x *MoveSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSnippetRequest.ProtoReflect.Descriptor instead.
func (*MoveSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{10}
}

func (x *MoveSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

func (x *MoveSnippetRequest) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *MoveSnippetRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

// SearchSnippetsRequest 结构化搜索请求（重设计）
type SearchSnippetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSnippetsRequest) Reset() {
	*x = SearchSnippetsRequest{}
	mi := &file_note_note_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSnippetsRequest) ProtoMessage() {}

func (x *SearchSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSnippetsRequest.ProtoReflect.Descriptor instead.
func (*SearchSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{11}
}

func (x *SearchSnippetsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSnippetsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SearchSnippetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSnippetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPublicSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicSnippetRequest) Reset() {
	*x = GetPublicSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicSnippetRequest) ProtoMessage() {}

func (x *GetPublicSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicSnippetRequest.ProtoReflect.Descriptor instead.
func (*GetPublicSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetPublicSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

type FavoriteSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteSnippetRequest) Reset() {
	*x = FavoriteSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteSnippetRequest) ProtoMessage() {}

func (x *FavoriteSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteSnippetRequest.ProtoReflect.Descriptor instead.
func (*FavoriteSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{13}
}

func (x *FavoriteSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

type UnfavoriteSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfavoriteSnippetRequest) Reset() {
	*x = UnfavoriteSnippetRequest{}
	mi := &file_note_note_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfavoriteSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfavoriteSnippetRequest) ProtoMessage() {}

func (x *UnfavoriteSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfavoriteSnippetRequest.ProtoReflect.Descriptor instead.
func (*UnfavoriteSnippetRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{14}
}

func (x *UnfavoriteSnippetRequest) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

type FavoriteSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnippetId     int64                  `protobuf:"varint,1,opt,name=snippet_id,json=snippetId,proto3" json:"snippet_id,omitempty"`
	Favorite      bool                   `protobuf:"varint,2,opt,name=favorite,proto3" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteSnippetResponse) Reset() {
	*x = FavoriteSnippetResponse{}
	mi := &file_note_note_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteSnippetResponse) ProtoMessage() {}

func (x *FavoriteSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteSnippetResponse.ProtoReflect.Descriptor instead.
func (*FavoriteSnippetResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{15}
}

func (x *FavoriteSnippetResponse) GetSnippetId() int64 {
	if x != nil {
		return x.SnippetId
	}
	return 0
}

func (x *FavoriteSnippetResponse) GetFavorite() bool {
	if x != nil {
		return x.Favorite
	}
	return false
}

type CreateSnippetFromTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    int64                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Visibility    string                 `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetFromTemplateRequest) Reset() {
	*x = CreateSnippetFromTemplateRequest{}
	mi := &file_note_note_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetFromTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetFromTemplateRequest) ProtoMessage() {}

func (x *CreateSnippetFromTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetFromTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateSnippetFromTemplateRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSnippetFromTemplateRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *CreateSnippetFromTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSnippetFromTemplateRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

// ── Group Messages ──
type GroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId      *int64                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	ChildrenCount int32                  `protobuf:"varint,8,opt,name=children_count,json=childrenCount,proto3" json:"children_count,omitempty"`
	SnippetCount  int32                  `protobuf:"varint,9,opt,name=snippet_count,json=snippetCount,proto3" json:"snippet_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_note_note_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{17}
}

func (x *GroupResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GroupResponse) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *GroupResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupResponse) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *GroupResponse) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GroupResponse) GetChildrenCount() int32 {
	if x != nil {
		return x.ChildrenCount
	}
	return 0
}

func (x *GroupResponse) GetSnippetCount() int32 {
	if x != nil {
		return x.SnippetCount
	}
	return 0
}

func (x *GroupResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_note_note_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{18}
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_note_note_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupResponse       `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_note_note_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListGroupsResponse) GetGroups() []*GroupResponse {
	if x != nil {
		return x.Groups
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_note_note_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{21}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,5,opt,name=visibility,proto3" json:"visibility,omitempty"`
	SortOrder     *int32                 `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_note_note_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *UpdateGroupRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_note_note_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_note_note_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteGroupResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ── Tag Messages ──
type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_note_note_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{25}
}

func (x *TagResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *TagResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TagResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_note_note_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{26}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*TagResponse         `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_note_note_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{27}
}

func (x *ListTagsResponse) GetTags() []*TagResponse {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_note_note_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{28}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_note_note_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int64                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_note_note_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteTagRequest) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_note_note_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteTagResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ── Template Messages ──
type TemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateResponse) Reset() {
	*x = TemplateResponse{}
	mi := &file_note_note_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateResponse) ProtoMessage() {}

func (x *TemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateResponse.ProtoReflect.Descriptor instead.
func (*TemplateResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{32}
}

func (x *TemplateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TemplateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_note_note_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{33}
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateResponse    `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_note_note_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{34}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateResponse {
	if x != nil {
		return x.Templates
	}
	return nil
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_note_note_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{35}
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

// ── Upload ──
type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_note_note_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{36}
}

func (x *UploadFileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_note_note_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_note_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_note_note_api_proto_rawDescGZIP(), []int{37}
}

func (x *UploadFileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_note_note_api_proto protoreflect.FileDescriptor

const file_note_note_api_proto_rawDesc = "" +
	"\n" +
	"\x13note/note_api.proto\x12\x04note\x1a\x1cgoogle/api/annotations.proto\"\xaf\x01\n" +
	"\x14CreateSnippetRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\x12\x1e\n" +
	"\bgroup_id\x18\x05 \x01(\x03H\x00R\agroupId\x88\x01\x01B\v\n" +
	"\t_group_id\"2\n" +
	"\x11GetSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\"\xfe\x01\n" +
	"\x13ListSnippetsRequest\x12\x1e\n" +
	"\bgroup_id\x18\x01 \x01(\x03H\x00R\agroupId\x88\x01\x01\x12\x1a\n" +
	"\x06tag_id\x18\x02 \x01(\x03H\x01R\x05tagId\x88\x01\x01\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04typeB\v\n" +
	"\t_group_idB\t\n" +
	"\a_tag_id\"\xa1\x01\n" +
	"\x14UpdateSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\"\xa2\x03\n" +
	"\x0fSnippetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\tR\n" +
	"visibility\x12\x19\n" +
	"\bgroup_id\x18\v \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x17\n" +
	"\atag_ids\x18\x0e \x03(\x03R\x06tagIds\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x0f \x01(\x05R\tsortOrder\"\x85\x01\n" +
	"\x14ListSnippetsResponse\x121\n" +
	"\bsnippets\x18\x01 \x03(\v2\x15.note.SnippetResponseR\bsnippets\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"5\n" +
	"\x14DeleteSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\"'\n" +
	"\x15DeleteSnippetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"O\n" +
	"\x15SetSnippetTagsRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\x12\x17\n" +
	"\atag_ids\x18\x02 \x03(\x03R\x06tagIds\"\x18\n" +
	"\x16SetSnippetTagsResponse\"\x93\x01\n" +
	"\x12MoveSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\x12\x1e\n" +
	"\bgroup_id\x18\x02 \x01(\x03H\x00R\agroupId\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05H\x01R\tsortOrder\x88\x01\x01B\v\n" +
	"\t_group_idB\r\n" +
	"\v_sort_order\"{\n" +
	"\x15SearchSnippetsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"8\n" +
	"\x17GetPublicSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\"7\n" +
	"\x16FavoriteSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\"9\n" +
	"\x18UnfavoriteSnippetRequest\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\"T\n" +
	"\x17FavoriteSnippetResponse\x12\x1d\n" +
	"\n" +
	"snippet_id\x18\x01 \x01(\x03R\tsnippetId\x12\x1a\n" +
	"\bfavorite\x18\x02 \x01(\bR\bfavorite\"y\n" +
	" CreateSnippetFromTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x03R\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"visibility\x18\x03 \x01(\tR\n" +
	"visibility\"\xe9\x02\n" +
	"\rGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12 \n" +
	"\tparent_id\x18\x04 \x01(\x03H\x00R\bparentId\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12%\n" +
	"\x0echildren_count\x18\b \x01(\x05R\rchildrenCount\x12#\n" +
	"\rsnippet_count\x18\t \x01(\x05R\fsnippetCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_parent_id\"\x13\n" +
	"\x11ListGroupsRequest\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"A\n" +
	"\x12ListGroupsResponse\x12+\n" +
	"\x06groups\x18\x01 \x03(\v2\x13.note.GroupResponseR\x06groups\"\x9a\x01\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x03H\x00R\bparentId\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibilityB\f\n" +
	"\n" +
	"_parent_id\"\xe8\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x00R\bparentId\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x05 \x01(\tR\n" +
	"visibility\x12\"\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05H\x01R\tsortOrder\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_sort_order\"/\n" +
	"\x12DeleteGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"%\n" +
	"\x13DeleteGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x81\x01\n" +
	"\vTagResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x11\n" +
	"\x0fListTagsRequest\"9\n" +
	"\x10ListTagsResponse\x12%\n" +
	"\x04tags\x18\x01 \x03(\v2\x11.note.TagResponseR\x04tags\"<\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"S\n" +
	"\x10UpdateTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\")\n" +
	"\x10DeleteTagRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x03R\x05tagId\"#\n" +
	"\x11DeleteTagResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\x10TemplateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x16\n" +
	"\x14ListTemplatesRequest\"M\n" +
	"\x15ListTemplatesResponse\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.note.TemplateResponseR\ttemplates\"5\n" +
	"\x12GetTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"L\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"T\n" +
	"\x12UploadFileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size2\xf5\x16\n" +
	"\vNoteService\x12h\n" +
	"\fListSnippets\x12\x19.note.ListSnippetsRequest\x1a\x1a.note.ListSnippetsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/notes/me/snippets\x12e\n" +
	"\rCreateSnippet\x12\x1a.note.CreateSnippetRequest\x1a\x15.note.SnippetResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/notes/snippets\x12i\n" +
	"\n" +
	"GetSnippet\x12\x17.note.GetSnippetRequest\x1a\x15.note.SnippetResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/notes/snippets/{snippet_id}\x12r\n" +
	"\rUpdateSnippet\x12\x1a.note.UpdateSnippetRequest\x1a\x15.note.SnippetResponse\".\x82\xd3\xe4\x93\x02(:\x01*\x1a#/api/v1/notes/snippets/{snippet_id}\x12u\n" +
	"\rDeleteSnippet\x12\x1a.note.DeleteSnippetRequest\x1a\x1b.note.DeleteSnippetResponse\"+\x82\xd3\xe4\x93\x02%*#/api/v1/notes/snippets/{snippet_id}\x12\x80\x01\n" +
	"\x0eSetSnippetTags\x12\x1b.note.SetSnippetTagsRequest\x1a\x1c.note.SetSnippetTagsResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\x1a(/api/v1/notes/snippets/{snippet_id}/tags\x12s\n" +
	"\vMoveSnippet\x12\x18.note.MoveSnippetRequest\x1a\x15.note.SnippetResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\x1a(/api/v1/notes/snippets/{snippet_id}/move\x12p\n" +
	"\x0eSearchSnippets\x12\x1b.note.SearchSnippetsRequest\x1a\x1a.note.ListSnippetsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/notes/snippets/search\x12H\n" +
	"\x10GetPublicSnippet\x12\x1d.note.GetPublicSnippetRequest\x1a\x15.note.SnippetResponse\x12\x84\x01\n" +
	"\x0fFavoriteSnippet\x12\x1c.note.FavoriteSnippetRequest\x1a\x1d.note.FavoriteSnippetResponse\"4\x82\xd3\xe4\x93\x02.\",/api/v1/notes/snippets/{snippet_id}/favorite\x12\x88\x01\n" +
	"\x11UnfavoriteSnippet\x12\x1e.note.UnfavoriteSnippetRequest\x1a\x1d.note.FavoriteSnippetResponse\"4\x82\xd3\xe4\x93\x02.*,/api/v1/notes/snippets/{snippet_id}/favorite\x12\x8b\x01\n" +
	"\x19CreateSnippetFromTemplate\x12&.note.CreateSnippetFromTemplateRequest\x1a\x15.note.SnippetResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/notes/snippets/from-template\x12u\n" +
	"\x12ListRecentSnippets\x12\x19.note.ListSnippetsRequest\x1a\x1a.note.ListSnippetsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/notes/me/snippets/recent\x12u\n" +
	"\x12ListSharedSnippets\x12\x19.note.ListSnippetsRequest\x1a\x1a.note.ListSnippetsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/notes/me/snippets/shared\x12z\n" +
	"\x14ListFavoriteSnippets\x12\x19.note.ListSnippetsRequest\x1a\x1a.note.ListSnippetsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/notes/me/snippets/favorites\x12]\n" +
	"\n" +
	"ListGroups\x12\x17.note.ListGroupsRequest\x1a\x18.note.ListGroupsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/notes/groups\x12_\n" +
	"\bGetGroup\x12\x15.note.GetGroupRequest\x1a\x13.note.GroupResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/notes/groups/{group_id}\x12]\n" +
	"\vCreateGroup\x12\x18.note.CreateGroupRequest\x1a\x13.note.GroupResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/notes/groups\x12h\n" +
	"\vUpdateGroup\x12\x18.note.UpdateGroupRequest\x1a\x13.note.GroupResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/v1/notes/groups/{group_id}\x12k\n" +
	"\vDeleteGroup\x12\x18.note.DeleteGroupRequest\x1a\x19.note.DeleteGroupResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/notes/groups/{group_id}\x12U\n" +
	"\bListTags\x12\x15.note.ListTagsRequest\x1a\x16.note.ListTagsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/notes/tags\x12U\n" +
	"\tCreateTag\x12\x16.note.CreateTagRequest\x1a\x11.note.TagResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/notes/tags\x12^\n" +
	"\tUpdateTag\x12\x16.note.UpdateTagRequest\x1a\x11.note.TagResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/v1/notes/tags/{tag_id}\x12a\n" +
	"\tDeleteTag\x12\x16.note.DeleteTagRequest\x1a\x17.note.DeleteTagResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/notes/tags/{tag_id}\x12i\n" +
	"\rListTemplates\x12\x1a.note.ListTemplatesRequest\x1a\x1b.note.ListTemplatesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/notes/templates\x12n\n" +
	"\vGetTemplate\x12\x18.note.GetTemplateRequest\x1a\x16.note.TemplateResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/notes/templates/{template_id}\x12?\n" +
	"\n" +
	"UploadFile\x12\x17.note.UploadFileRequest\x1a\x18.note.UploadFileResponseB'Z%github.com/luckysxx/common/proto/noteb\x06proto3"

var (
	file_note_note_api_proto_rawDescOnce sync.Once
	file_note_note_api_proto_rawDescData []byte
)

func file_note_note_api_proto_rawDescGZIP() []byte {
	file_note_note_api_proto_rawDescOnce.Do(func() {
		file_note_note_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_note_api_proto_rawDesc), len(file_note_note_api_proto_rawDesc)))
	})
	return file_note_note_api_proto_rawDescData
}

var file_note_note_api_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_note_note_api_proto_goTypes = []any{
	(*CreateSnippetRequest)(nil),             // 0: note.CreateSnippetRequest
	(*GetSnippetRequest)(nil),                // 1: note.GetSnippetRequest
	(*ListSnippetsRequest)(nil),              // 2: note.ListSnippetsRequest
	(*UpdateSnippetRequest)(nil),             // 3: note.UpdateSnippetRequest
	(*SnippetResponse)(nil),                  // 4: note.SnippetResponse
	(*ListSnippetsResponse)(nil),             // 5: note.ListSnippetsResponse
	(*DeleteSnippetRequest)(nil),             // 6: note.DeleteSnippetRequest
	(*DeleteSnippetResponse)(nil),            // 7: note.DeleteSnippetResponse
	(*SetSnippetTagsRequest)(nil),            // 8: note.SetSnippetTagsRequest
	(*SetSnippetTagsResponse)(nil),           // 9: note.SetSnippetTagsResponse
	(*MoveSnippetRequest)(nil),               // 10: note.MoveSnippetRequest
	(*SearchSnippetsRequest)(nil),            // 11: note.SearchSnippetsRequest
	(*GetPublicSnippetRequest)(nil),          // 12: note.GetPublicSnippetRequest
	(*FavoriteSnippetRequest)(nil),           // 13: note.FavoriteSnippetRequest
	(*UnfavoriteSnippetRequest)(nil),         // 14: note.UnfavoriteSnippetRequest
	(*FavoriteSnippetResponse)(nil),          // 15: note.FavoriteSnippetResponse
	(*CreateSnippetFromTemplateRequest)(nil), // 16: note.CreateSnippetFromTemplateRequest
	(*GroupResponse)(nil),                    // 17: note.GroupResponse
	(*ListGroupsRequest)(nil),                // 18: note.ListGroupsRequest
	(*GetGroupRequest)(nil),                  // 19: note.GetGroupRequest
	(*ListGroupsResponse)(nil),               // 20: note.ListGroupsResponse
	(*CreateGroupRequest)(nil),               // 21: note.CreateGroupRequest
	(*UpdateGroupRequest)(nil),               // 22: note.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),               // 23: note.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),              // 24: note.DeleteGroupResponse
	(*TagResponse)(nil),                      // 25: note.TagResponse
	(*ListTagsRequest)(nil),                  // 26: note.ListTagsRequest
	(*ListTagsResponse)(nil),                 // 27: note.ListTagsResponse
	(*CreateTagRequest)(nil),                 // 28: note.CreateTagRequest
	(*UpdateTagRequest)(nil),                 // 29: note.UpdateTagRequest
	(*DeleteTagRequest)(nil),                 // 30: note.DeleteTagRequest
	(*DeleteTagResponse)(nil),                // 31: note.DeleteTagResponse
	(*TemplateResponse)(nil),                 // 32: note.TemplateResponse
	(*ListTemplatesRequest)(nil),             // 33: note.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),            // 34: note.ListTemplatesResponse
	(*GetTemplateRequest)(nil),               // 35: note.GetTemplateRequest
	(*UploadFileRequest)(nil),                // 36: note.UploadFileRequest
	(*UploadFileResponse)(nil),               // 37: note.UploadFileResponse
}
var file_note_note_api_proto_depIdxs = []int32{
	4,  // 0: note.ListSnippetsResponse.snippets:type_name -> note.SnippetResponse
	17, // 1: note.ListGroupsResponse.groups:type_name -> note.GroupResponse
	25, // 2: note.ListTagsResponse.tags:type_name -> note.TagResponse
	32, // 3: note.ListTemplatesResponse.templates:type_name -> note.TemplateResponse
	2,  // 4: note.NoteService.ListSnippets:input_type -> note.ListSnippetsRequest
	0,  // 5: note.NoteService.CreateSnippet:input_type -> note.CreateSnippetRequest
	1,  // 6: note.NoteService.GetSnippet:input_type -> note.GetSnippetRequest
	3,  // 7: note.NoteService.UpdateSnippet:input_type -> note.UpdateSnippetRequest
	6,  // 8: note.NoteService.DeleteSnippet:input_type -> note.DeleteSnippetRequest
	8,  // 9: note.NoteService.SetSnippetTags:input_type -> note.SetSnippetTagsRequest
	10, // 10: note.NoteService.MoveSnippet:input_type -> note.MoveSnippetRequest
	11, // 11: note.NoteService.SearchSnippets:input_type -> note.SearchSnippetsRequest
	12, // 12: note.NoteService.GetPublicSnippet:input_type -> note.GetPublicSnippetRequest
	13, // 13: note.NoteService.FavoriteSnippet:input_type -> note.FavoriteSnippetRequest
	14, // 14: note.NoteService.UnfavoriteSnippet:input_type -> note.UnfavoriteSnippetRequest
	16, // 15: note.NoteService.CreateSnippetFromTemplate:input_type -> note.CreateSnippetFromTemplateRequest
	2,  // 16: note.NoteService.ListRecentSnippets:input_type -> note.ListSnippetsRequest
	2,  // 17: note.NoteService.ListSharedSnippets:input_type -> note.ListSnippetsRequest
	2,  // 18: note.NoteService.ListFavoriteSnippets:input_type -> note.ListSnippetsRequest
	18, // 19: note.NoteService.ListGroups:input_type -> note.ListGroupsRequest
	19, // 20: note.NoteService.GetGroup:input_type -> note.GetGroupRequest
	21, // 21: note.NoteService.CreateGroup:input_type -> note.CreateGroupRequest
	22, // 22: note.NoteService.UpdateGroup:input_type -> note.UpdateGroupRequest
	23, // 23: note.NoteService.DeleteGroup:input_type -> note.DeleteGroupRequest
	26, // 24: note.NoteService.ListTags:input_type -> note.ListTagsRequest
	28, // 25: note.NoteService.CreateTag:input_type -> note.CreateTagRequest
	29, // 26: note.NoteService.UpdateTag:input_type -> note.UpdateTagRequest
	30, // 27: note.NoteService.DeleteTag:input_type -> note.DeleteTagRequest
	33, // 28: note.NoteService.ListTemplates:input_type -> note.ListTemplatesRequest
	35, // 29: note.NoteService.GetTemplate:input_type -> note.GetTemplateRequest
	36, // 30: note.NoteService.UploadFile:input_type -> note.UploadFileRequest
	5,  // 31: note.NoteService.ListSnippets:output_type -> note.ListSnippetsResponse
	4,  // 32: note.NoteService.CreateSnippet:output_type -> note.SnippetResponse
	4,  // 33: note.NoteService.GetSnippet:output_type -> note.SnippetResponse
	4,  // 34: note.NoteService.UpdateSnippet:output_type -> note.SnippetResponse
	7,  // 35: note.NoteService.DeleteSnippet:output_type -> note.DeleteSnippetResponse
	9,  // 36: note.NoteService.SetSnippetTags:output_type -> note.SetSnippetTagsResponse
	4,  // 37: note.NoteService.MoveSnippet:output_type -> note.SnippetResponse
	5,  // 38: note.NoteService.SearchSnippets:output_type -> note.ListSnippetsResponse
	4,  // 39: note.NoteService.GetPublicSnippet:output_type -> note.SnippetResponse
	15, // 40: note.NoteService.FavoriteSnippet:output_type -> note.FavoriteSnippetResponse
	15, // 41: note.NoteService.UnfavoriteSnippet:output_type -> note.FavoriteSnippetResponse
	4,  // 42: note.NoteService.CreateSnippetFromTemplate:output_type -> note.SnippetResponse
	5,  // 43: note.NoteService.ListRecentSnippets:output_type -> note.ListSnippetsResponse
	5,  // 44: note.NoteService.ListSharedSnippets:output_type -> note.ListSnippetsResponse
	5,  // 45: note.NoteService.ListFavoriteSnippets:output_type -> note.ListSnippetsResponse
	20, // 46: note.NoteService.ListGroups:output_type -> note.ListGroupsResponse
	17, // 47: note.NoteService.GetGroup:output_type -> note.GroupResponse
	17, // 48: note.NoteService.CreateGroup:output_type -> note.GroupResponse
	17, // 49: note.NoteService.UpdateGroup:output_type -> note.GroupResponse
	24, // 50: note.NoteService.DeleteGroup:output_type -> note.DeleteGroupResponse
	27, // 51: note.NoteService.ListTags:output_type -> note.ListTagsResponse
	25, // 52: note.NoteService.CreateTag:output_type -> note.TagResponse
	25, // 53: note.NoteService.UpdateTag:output_type -> note.TagResponse
	31, // 54: note.NoteService.DeleteTag:output_type -> note.DeleteTagResponse
	34, // 55: note.NoteService.ListTemplates:output_type -> note.ListTemplatesResponse
	32, // 56: note.NoteService.GetTemplate:output_type -> note.TemplateResponse
	37, // 57: note.NoteService.UploadFile:output_type -> note.UploadFileResponse
	31, // [31:58] is the sub-list for method output_type
	4,  // [4:31] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_note_note_api_proto_init() }
func file_note_note_api_proto_init() {
	if File_note_note_api_proto != nil {
		return
	}
	file_note_note_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_note_note_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_note_note_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_note_note_api_proto_msgTypes[17].OneofWrappers = []any{}
	file_note_note_api_proto_msgTypes[21].OneofWrappers = []any{}
	file_note_note_api_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_note_api_proto_rawDesc), len(file_note_note_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_note_api_proto_goTypes,
		DependencyIndexes: file_note_note_api_proto_depIdxs,
		MessageInfos:      file_note_note_api_proto_msgTypes,
	}.Build()
	File_note_note_api_proto = out.File
	file_note_note_api_proto_goTypes = nil
	file_note_note_api_proto_depIdxs = nil
}
