// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/idgen/idgen.proto

package idgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDGenerator_NextID_FullMethodName = "/idgen.IDGenerator/NextID"
)

// IDGeneratorClient is the client API for IDGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDGeneratorClient interface {
	NextID(ctx context.Context, in *NextIDRequest, opts ...grpc.CallOption) (*NextIDResponse, error)
}

type iDGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIDGeneratorClient(cc grpc.ClientConnInterface) IDGeneratorClient {
	return &iDGeneratorClient{cc}
}

func (c *iDGeneratorClient) NextID(ctx context.Context, in *NextIDRequest, opts ...grpc.CallOption) (*NextIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextIDResponse)
	err := c.cc.Invoke(ctx, IDGenerator_NextID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDGeneratorServer is the server API for IDGenerator service.
// All implementations must embed UnimplementedIDGeneratorServer
// for forward compatibility.
type IDGeneratorServer interface {
	NextID(context.Context, *NextIDRequest) (*NextIDResponse, error)
	mustEmbedUnimplementedIDGeneratorServer()
}

// UnimplementedIDGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDGeneratorServer struct{}

func (UnimplementedIDGeneratorServer) NextID(context.Context, *NextIDRequest) (*NextIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NextID not implemented")
}
func (UnimplementedIDGeneratorServer) mustEmbedUnimplementedIDGeneratorServer() {}
func (UnimplementedIDGeneratorServer) testEmbeddedByValue()                     {}

// UnsafeIDGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDGeneratorServer will
// result in compilation errors.
type UnsafeIDGeneratorServer interface {
	mustEmbedUnimplementedIDGeneratorServer()
}

func RegisterIDGeneratorServer(s grpc.ServiceRegistrar, srv IDGeneratorServer) {
	// If the following call panics, it indicates UnimplementedIDGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDGenerator_ServiceDesc, srv)
}

func _IDGenerator_NextID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDGeneratorServer).NextID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDGenerator_NextID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDGeneratorServer).NextID(ctx, req.(*NextIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDGenerator_ServiceDesc is the grpc.ServiceDesc for IDGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idgen.IDGenerator",
	HandlerType: (*IDGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextID",
			Handler:    _IDGenerator_NextID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/idgen/idgen.proto",
}
