// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/idgen/idgen.proto

package idgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextIDRequest) Reset() {
	*x = NextIDRequest{}
	mi := &file_proto_idgen_idgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextIDRequest) ProtoMessage() {}

func (x *NextIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idgen_idgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextIDRequest.ProtoReflect.Descriptor instead.
func (*NextIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_idgen_idgen_proto_rawDescGZIP(), []int{0}
}

type NextIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextIDResponse) Reset() {
	*x = NextIDResponse{}
	mi := &file_proto_idgen_idgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextIDResponse) ProtoMessage() {}

func (x *NextIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idgen_idgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextIDResponse.ProtoReflect.Descriptor instead.
func (*NextIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_idgen_idgen_proto_rawDescGZIP(), []int{1}
}

func (x *NextIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_idgen_idgen_proto protoreflect.FileDescriptor

const file_proto_idgen_idgen_proto_rawDesc = "" +
	"\n" +
	"\x17proto/idgen/idgen.proto\x12\x05idgen\"\x0f\n" +
	"\rNextIDRequest\" \n" +
	"\x0eNextIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2F\n" +
	"\vIDGenerator\x127\n" +
	"\x06NextID\x12\x14.idgen.NextIDRequest\x1a\x15.idgen.NextIDResponse\"\x00B(Z&github.com/luckysxx/common/proto/idgenb\x06proto3"

var (
	file_proto_idgen_idgen_proto_rawDescOnce sync.Once
	file_proto_idgen_idgen_proto_rawDescData []byte
)

func file_proto_idgen_idgen_proto_rawDescGZIP() []byte {
	file_proto_idgen_idgen_proto_rawDescOnce.Do(func() {
		file_proto_idgen_idgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_idgen_idgen_proto_rawDesc), len(file_proto_idgen_idgen_proto_rawDesc)))
	})
	return file_proto_idgen_idgen_proto_rawDescData
}

var file_proto_idgen_idgen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_idgen_idgen_proto_goTypes = []any{
	(*NextIDRequest)(nil),  // 0: idgen.NextIDRequest
	(*NextIDResponse)(nil), // 1: idgen.NextIDResponse
}
var file_proto_idgen_idgen_proto_depIdxs = []int32{
	0, // 0: idgen.IDGenerator.NextID:input_type -> idgen.NextIDRequest
	1, // 1: idgen.IDGenerator.NextID:output_type -> idgen.NextIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_idgen_idgen_proto_init() }
func file_proto_idgen_idgen_proto_init() {
	if File_proto_idgen_idgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_idgen_idgen_proto_rawDesc), len(file_proto_idgen_idgen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_idgen_idgen_proto_goTypes,
		DependencyIndexes: file_proto_idgen_idgen_proto_depIdxs,
		MessageInfos:      file_proto_idgen_idgen_proto_msgTypes,
	}.Build()
	File_proto_idgen_idgen_proto = out.File
	file_proto_idgen_idgen_proto_goTypes = nil
	file_proto_idgen_idgen_proto_depIdxs = nil
}
